### ISSUE TITLE
not support Fooocus 2.1.781

### ISSUE THREAD

**Issue by wqjuser** [mrhan1993/Fooocus-API#50]
when i use Fooocus version is 2.1.781 and use  /v1/generation/text-to-image Api，then the console returned the following error message:
[Fooocus] Processing prompts ...
Worker error: apply_wildcards() missing 1 required positional argument: 'i'
[Task Queue] Finish task with error, seq=1

**Comment by konieshadow** [comment]
Which version of Fooocus-API were you using? I just tested and it works fine in Fooocus-API v0.3.10.

**Comment by wqjuser** [comment]
the problem maybe i changed some code
